import Head from "next/head";
import { Inter } from "@next/font/google";
import AddTodoSection from "@/lib/components/todo/AddTodoSection";
import TodoSection from "@/lib/components/todo/TodoSection";
import { useTodoStore } from "@/lib/store/TodoStore";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const todos = useTodoStore((state) => state.todos);

  return (
    <>
      <Head>
        <title>Checklist app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-olive-one p-0 selection:bg-green-two md:py-24 md:px-8">
        <main
          className={`${inter.className} mx-auto min-h-screen max-w-none rounded-none bg-cream-four px-5 py-10 outline-none md:min-h-max md:max-w-[60rem] md:rounded-2xl md:px-8 md:outline md:outline-4 md:outline-offset-8 md:outline-cream-four`}
        >
          <h1 className="text-2xl font-bold text-gray-three">Dashboard</h1>
          <div className="mt-10">
            <AddTodoSection />
            {todos.map((todo) => (
              <TodoSection key={todo.id} todo={todo} />
            ))}
          </div>
        </main>
      </div>
    </>
  );
}
